# Generated by Django 2.2 on 2020-06-05 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tdlist', '0003_business_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='author',
        ),
    ]
